### PR TITLE
RNMT-2669 Cipher Plugin - Upgrade to SQLite 3.26 + 64-bit support

### PR DESCRIPTION
**Pull request by pmaroco**
## Description
This PR includes the support of 64-bits libraries (provided by upstream tag **3.5.9**) and the upgrade of SQLite to 3.26 (provided by upstream tag **4.0.1**).

The latest version offered by OutSystems (**3.4.0**-OS2) was locked to version **3.4.0** and included the following two commits (**-OS** and **-OS2** tags) over upstream:

- **Increased CursorWindow max** - [`commit: 80bbf4bc4ce6318f8bdc4c636941dd1610938558`](https://github.com/OutSystems/android-database-sqlcipher/commit/80bbf4bc4ce6318f8bdc4c636941dd1610938558)
  - This change allowed queries to return results larger than ~500 kB. This mechanism was dropped in a release prior to version **4.0.1** and this change does not need to be applied over upstream.

- **Changed queries to bind arguments depending on their runtime type.** - [`commit: 8e4fe8b82b4d2040fa2debf940d47ae0edad8f20`](https://github.com/OutSystems/android-database-sqlcipher/commit/8e4fe8b82b4d2040fa2debf940d47ae0edad8f20)
  - This modification changed queries to bind arguments depending on their runtime type, by changing the type of bindArgs argument from `Query` methods from `String[]` to `Object[]`. Version **4.0.1** already provides the aforementioned methods with both signatures and therefore this change does not need to be applied over upstream.

Moreover, a fallback legacy method was [applied over upstream](https://github.com/OutSystems/android-database-sqlcipher/commit/13bfdc5abbee610e393a888685a9b73952c9a29f) to deal with the problems in the encoding/decoding process of complex password characters.

## Context

References https://outsystemsrd.atlassian.net/browse/RNMT-2669

## Type of changes

- [x] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [ ] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Native Code
- [ ] JS API

## Tests

Manual tests have been performed (using **Test Plugins App with Ciphered** and a custom app using **Barcode Scanner + CardIO + Cipher Local Storage** plugin). Automatic tests and QA certification are currently on-going.

## Checklist

- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

### CODE REVIEW

**Review by EiyuuZack — APPROVED** [review]
Looks good to me. Very surgical 👍

**Comment by EiyuuZack** [comment]
May I add, great job on the PR description. Answered questions I did not know I had 👍 Also pointing out the single relevant commit is a nice touch. I also suggest adding `?w=1` after opening the commit URL to filter out whitespace from the diff.

**Comment by usernuno** [comment]
Pseudo-useless information: the commit message about the ~500kB query result is incorrect. The default value of SQLite is 1MB, not 512kB.

**Review by luissilvaos — APPROVED** [review]

**Comment by pmaroco** [comment]
Although the pull request PR has 2 green approvals and 0 blocks, I'm going to close it *without* merging it to *master* branch. This decision was made due to an error discovered during the plugin certification while upgrading an app using Cipher Local Storage 3.8.10.2 or 3.5.9 to version 4.X, resulting in an inaccessible database after the upgrade. We will tackle this issue later in *RNMT-2950* (https://outsystemsrd.atlassian.net/browse/RNMT-2950).
However, due to the due date imposed by Google and the pressure from the support team, I will open a new PR just including the 64-bit support (without the upgrade to SQLite 3.26) to be released ASAP.

**Pull request closed without merging**
